# Release and Publish to NPM
# Triggered manually (at this point) from a specified branch/tag will perform the `npm run release`
name: publish-npm

# Run on workflow dispatch
# Currently no custom input
on:
  workflow_dispatch:

jobs:
  build:
    # Runs on Ubuntu-latest
    # with node version(s) 12.16.3
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['12.16.3']

    # Checks out the appropriate branch (github.ref)
    # Creates release tag
    # Publishes release tag (ish, actually the current ref but on which the tag was based)
    # Todo: fixup
    steps:
      - name: Checking out ${{ github.ref_name }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build and release tag
        run: npm run release
        env:
          GIT_AUTHOR_NAME: 'kenjdavidson'
          GIT_AUTHOR_EMAIL: 'ken.j.davidson@live.ca' 
          GIT_COMMITTER_NAME: 'kenjdavidson'
          GIT_COMMITTER_EMAIL: 'ken.j.davidson@live.ca' 
      - name: Publish released tag to NPM
        run: npm run publish-npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}          
