# Test and build all environments for the library
# Currently this is a manual process during testing - but will be done on PUSH/PULL_REQUEST eventually
name: Test and Build

on: workflow_dispatch

jobs:
  build-js:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['12.16.3']        
    steps:
      - name: Check out ${{ github.ref_name }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Run build
        run: npm run build
    
  build-java:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['12.16.3'] 
        
    steps:
      - name: Check out ${{ github.ref_name }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'         
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Install dependencies
        run: npm ci
      - name: Build with Gradle
        run: ./gradlew build
        
  build-ios:
    runs-on: mac-latest
    
    steps:
      - name: Check out ${{ github.ref_name }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
  
